# Generated by Django 3.2.6 on 2021-08-16 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210816_1045'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='todoitem',
            name='name of constraint',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 16, 10, 48, 1, 287738)),
        ),
    ]
